server:
  baseUrl: http://localhost:3000/  # where can get the picture
  imageUrl: images/
  imageServerDir: /Users/iammiind/Desktop/SE331-lab07/web/images/
# C:/lab/lab07/web/images/
---
spring:
  profiles: local
server:
  baseUrl: http://localhost:8080/
  imageUrl: student/images/
---
spring:
  profiles: remote
server:
  baseUrl: https://s3-ap-southeast-1.amazonaws.com/se331/
  imageUrl: pics/

